#!/usr/bin/env python3
# Ensure the project root is importable when this script is run directly
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

"""Evaluation script: retrieval Precision@k and LLM-as-judge grounding score.

Usage
-----
    python scripts/evaluate.py                   # runs built-in QA set
    python scripts/evaluate.py --qa-file qa.json # runs a custom QA JSON file

QA file format (JSON list)
--------------------------
[
  {
    "question": "What is the refund policy?",
    "expected_keywords": ["refund", "return", "30 days"]
  },
  ...
]

Output
------
Prints a JSON report and writes ``evaluation_results.json`` to the project root.
"""

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Dict, List

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Built-in QA pairs — replace / extend with domain-specific questions
# ---------------------------------------------------------------------------
DEFAULT_QA_PAIRS: List[Dict] = [
    {
        "question": "What is the return and refund policy?",
        "expected_keywords": ["refund", "return", "days", "policy"],
    },
    {
        "question": "How do I contact customer support?",
        "expected_keywords": ["contact", "email", "phone", "support"],
    },
    {
        "question": "What payment methods are accepted?",
        "expected_keywords": ["payment", "credit", "card", "paypal"],
    },
]


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

def precision_at_k(retrieved_docs, relevant_keywords: List[str], k: int) -> float:
    """Keyword-based Precision@k.

    A retrieved chunk is considered relevant if it contains at least one of
    the expected keywords (case-insensitive). This is a lightweight proxy
    for human-labelled relevance judgements.

    Args:
        retrieved_docs: Documents returned by the retriever (already top-k).
        relevant_keywords: Keywords that should appear in a relevant chunk.
        k: Cutoff for precision calculation.

    Returns:
        Float in [0.0, 1.0].
    """
    if k == 0:
        return 0.0
    top_k_docs = retrieved_docs[:k]
    relevant_count = sum(
        1
        for doc in top_k_docs
        if any(kw.lower() in doc.page_content.lower() for kw in relevant_keywords)
    )
    return relevant_count / k


def reciprocal_rank(retrieved_docs, relevant_keywords: List[str]) -> float:
    """Mean Reciprocal Rank component for a single query.

    Args:
        retrieved_docs: Ordered list of retrieved Documents.
        relevant_keywords: Keywords indicating relevance.

    Returns:
        1/rank of the first relevant document, or 0 if none found.
    """
    for rank, doc in enumerate(retrieved_docs, start=1):
        if any(kw.lower() in doc.page_content.lower() for kw in relevant_keywords):
            return 1.0 / rank
    return 0.0


def llm_judge_score(response: str, has_context: bool) -> int:
    """Heuristic grounding judge.

    Scores 1 if the response is grounded (references context / gives an
    answer), 0 if it falls back to the "no information" phrase.

    Args:
        response: Text generated by the LLM.
        has_context: Whether any relevant chunks were retrieved.

    Returns:
        0 or 1.
    """
    refusal_phrases = [
        "i don't have enough information",
        "cannot answer",
        "no information",
        "not sure",
        "i'm not able to",
    ]
    is_refusal = any(phrase in response.lower() for phrase in refusal_phrases)
    # Penalise confident hallucination (answered with no context)
    if has_context and not is_refusal:
        return 1
    if not has_context and is_refusal:
        return 1  # correctly refused
    return 0


# ---------------------------------------------------------------------------
# Evaluation runner
# ---------------------------------------------------------------------------

def run_evaluation(qa_pairs: List[Dict]) -> Dict:
    """Run retrieval and generation evaluation over the QA set.

    Args:
        qa_pairs: List of ``{"question": str, "expected_keywords": list}`` dicts.

    Returns:
        Nested dict with retrieval and generation metrics.
    """
    from app.config import settings
    from app.generation.chain import generate_response_sync
    from app.retrieval.retriever import retrieve

    k = settings.retrieval_top_k
    retrieval_results = []
    generation_results = []
    total_precision = 0.0
    total_rr = 0.0

    for qa in qa_pairs:
        question = qa["question"]
        keywords = qa["expected_keywords"]

        logger.info(f"Evaluating: {question!r}")

        # --- Retrieval metrics ---
        docs = retrieve(question)
        p_k = precision_at_k(docs, keywords, k)
        rr = reciprocal_rank(docs, keywords)
        total_precision += p_k
        total_rr += rr

        retrieval_results.append(
            {
                "question": question,
                "precision_at_k": round(p_k, 3),
                "reciprocal_rank": round(rr, 3),
                "chunks_retrieved": len(docs),
                "top_sources": [d.metadata.get("source", "?") for d in docs[:2]],
            }
        )

        # --- Generation metrics ---
        response, gen_docs = generate_response_sync(question, [])
        score = llm_judge_score(response, bool(gen_docs))
        generation_results.append(
            {
                "question": question,
                "response_preview": response[:200],
                "grounded": bool(gen_docs),
                "llm_judge_score": score,
            }
        )

    n = len(qa_pairs)
    return {
        "retrieval": {
            "mean_precision_at_k": round(total_precision / n, 3) if n else 0,
            "mean_reciprocal_rank": round(total_rr / n, 3) if n else 0,
            "k": k,
            "results": retrieval_results,
        },
        "generation": {
            "mean_judge_score": round(
                sum(r["llm_judge_score"] for r in generation_results) / n, 3
            ) if n else 0,
            "results": generation_results,
        },
    }


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate RAG retrieval and generation quality.")
    parser.add_argument(
        "--qa-file",
        type=Path,
        default=None,
        help="Path to a JSON file with custom QA pairs.",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()

    if args.qa_file:
        if not args.qa_file.exists():
            logger.error(f"QA file not found: {args.qa_file}")
            sys.exit(1)
        qa_pairs = json.loads(args.qa_file.read_text(encoding="utf-8"))
        logger.info(f"Loaded {len(qa_pairs)} QA pairs from {args.qa_file}")
    else:
        qa_pairs = DEFAULT_QA_PAIRS
        logger.info(f"Using {len(qa_pairs)} built-in QA pairs")

    report = run_evaluation(qa_pairs)

    print("\n" + json.dumps(report, indent=2))

    output_path = Path("evaluation_results.json")
    output_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    logger.info(f"Report saved to {output_path}")

    # Print summary line
    r = report["retrieval"]
    g = report["generation"]
    print(
        f"\nSummary — Precision@{r['k']}: {r['mean_precision_at_k']} | "
        f"MRR: {r['mean_reciprocal_rank']} | "
        f"Judge Score: {g['mean_judge_score']}"
    )


if __name__ == "__main__":
    main()
